version: '3'
 
services:
    mysql-db:
        container_name: mysql5.7
        image: mysql:5.7
 
        ports:
          - "3305:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        command: 
          #['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']
          --wait_timeout=31536000
          --interactive_timeout=31536000
          --max_connections=1000
        volumes:
          - "./data:/var/lib/mysql"
          - "./log:/var/log"
          - "./conf:/etc/mysql/"
