auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: 192.168.12.61:9092
    name: 61-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.175:9092
    name: 175-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.87:9092
    name: 87-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.20.103:9092
    name: local-kafka(192.168.20.103)
    properties: {}
    readOnly: false
  - bootstrapServers: idc.dbpublic01.kd.net:9092,idc.dbpublic02.kd.net:9092,idc.dbpublic03.kd.net:9092
    name: idc.dbpublic01.kd.net:9092,idc.dbpublic02.kd.net:9092,idc.dbpublic03.kd.net:9092
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.70:9092
    name: 192.168.12.70:9092
    properties: {}
    readOnly: false
rbac:
  roles: []
webclient: {}
