auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: 192.168.12.61:9092
    name: 61-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.175:9092
    name: 175-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.87:9092
    name: 87-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.20.103:9092
    name: local-kafka(192.168.20.103)
    properties: {}
    readOnly: false
  - bootstrapServers: idc.dbpublic01.kd.net:9092,idc.dbpublic02.kd.net:9092,idc.dbpublic03.kd.net:9092
    name: idc.dbpublic01.kd.net:9092,idc.dbpublic02.kd.net:9092,idc.dbpublic03.kd.net:9092
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.70:9092,192.168.12.71:9092,192.168.12.74:9092
    name: 70-HA-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.245:9092
    name: 245-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: 192.168.12.244:9092
    name: 244-kafka
    properties: {}
    readOnly: false
  - bootstrapServers: db.public04.keendata.net:9092,db.public05.keendata.net:9092,db.public06.keendata.net:9092
    name: db.public04.keendata.net:9092,db.public05.keendata.net:9092,db.public06.keendata.net:9092
    properties: {}
    readOnly: false
rbac:
  roles: []
webclient: {}
