version: '2'
services:
    redis:
      image: redis
      container_name: redis
      #command: redis-server --requirepass 123456
      ports:
        - "6379:6379"
      volumes:
        - ./data:/data
